const itemToAbbreviationMap = {
    "Republic of Korea(대한민국)" : "KR",
    'Apple': 'AP',
    'Banana': 'BN',
    'Cherry': 'CH',
    'Grapes': 'GR',
    'Lemon': 'LM',
    'Orange': 'OR',
    'Pineapple': 'PP',
    'Strawberry1': 'SB',
    'Strawberry2': 'SB',
    'Strawberry3': 'SB',
    'Strawberry4': 'SB',
    'Strawberry5': 'SB',
    'Strawberry6': 'SB',
    'Strawberry7': 'SB',
    'Strawberry8': 'SB',
    'Strawberry9': 'SB',
    'Strawberry10': 'SB',
};